# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

from __future__ import print_statement
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint

# create an instance of the API class
api_instance = swagger_client.DefaultApi()
code = SXF # String | 3 letter IATA Code of the airport.

try: 
    # Airports
    api_response = api_instance.iataCodeGet(code)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling DefaultApi->iataCodeGet: %s\n" % e)